### ISSUE TITLE
Can I resize and setMime?

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud-extra-fields#1]
I just discovered that your library can do pagination and file uploads, damn I must be blind. I'm currently using https://github.com/samayo/bulletproof. 

Because it's secure and I can resize the image and setMime I want to accept, can I do that in your library?

**Comment by oscarotero** [comment]
You can validate the data before save it using the method `Table::dataToDatabase()`. [here's the documentation](https://github.com/oscarotero/simple-crud#data-validation). The `File` field does not validate or modify the data file, just upload and return the file path.

To validate input data, I use other library of mine: [form-manager](https://github.com/oscarotero/form-manager) that allows to create the forms and validate/sanitize input data, including the files.

Anyway, bulletproof seems a good choice too.

**Comment by elieobeid7** [comment]
Thanks a loy
